### ISSUE TITLE
Tree column names (ArcGIS Limitations)

### ISSUE THREAD

**Issue by Wjrmc** [OKFNau/open-council-data#1]
When converting Geelong Tree data to shapefiles we are getting some limitation on field header size. The max characters that shapefiles can store is 8 characters, so we are getting errors with the following fields:
- useful_life_min
- useful_life_max
- crown_width
- common_name
- location_type
- captured_date

See below for an FME screenshot of what the fields turn out to be:

![image](https://cloud.githubusercontent.com/assets/8185097/5641041/39e641b6-9684-11e4-971e-f8057fe3c125.png)

**Comment by stevage** [comment]
Thanks heaps for the report - I had no idea. Looks like there are [various implementation-specific workarounds](http://gis.stackexchange.com/questions/15784/how-to-bypass-10-character-limit-of-field-name-in-shapefiles), but for interoperability, best we keep under 10 characters.

So, how about:
- `ule_min`
- `ule_max`
- `crown`
- `common`
- `location`
- `captured`

**Comment by Wjrmc** [comment]
Yep sounds good, I'll give it a go.

--- Original Message ---

**Comment by stevage** [comment]
Closing as now using 10 character attributes everywhere. Not ideal really. Maybe would be better to have a specific fallback mechanism for shapefiles, which are discouraged anyway.
