### ISSUE TITLE
Standard Proposal - Council Wards

### ISSUE THREAD

**Issue by Wjrmc** [OKFNau/open-council-data#13]
ward_name - Ward name ie- Buckley, etc
councillor - The councillor that represents the region
portfolio - The councillor portfolio
lga - The council name (useful if wards data is combined)

**Comment by stevage** [comment]
https://github.com/OKFNau/open-council-data/commit/c347b3cdb27c9d23b1849eb25d70c8aa81443aca

**Comment by stevage** [comment]
Closing as per #19.
