### ISSUE TITLE
Standard Proposal - Council Customer Service Centres

### ISSUE THREAD

**Issue by Wjrmc** [OKFNau/open-council-data#14]
- lat
- lon
- name
- contact_ph
  (hours of operation)
  mon_hrs -
  tues_hrs -
  wed_hrs - 
  thu_hrs - 
  fri_hrs -
  sat_hrs -
  sun_hrs -

**Comment by stevage** [comment]
https://github.com/OKFNau/open-council-data/commit/c41ba4ca4d09c98f13b87bb014d6c19eeb9329e2
