### ISSUE TITLE
Different date format for garbage collection zones

### ISSUE THREAD

**Issue by stevage** [OKFNau/open-council-data#15]
Three problems with using ISO8601 recurring dates:
1. There's almost zero support for parsing them in any libraries
2. They're pretty hard to work with in non-programmatic contexts like colour coding on a map. Eg, there's no string matching you can do on an ISO8601 date to know that it's a Monday pickup.
3. They're not really human readable at all

I'm thinking an alternative format along the lines of:
- `_day`: eg Monday
- `_weeks`: eg 1 or 2
- `_start`: eg 2015-04-01, optional if every week

and maybe retain the current format as optional for complicated situations?
- `_sched`: ISO8601 with recurring interval.

**Comment by pwalsh** [comment]
Hey @stevage: surely ISO8601 dates are the most **widely** supported string format for dates?

If you just mean the recurring aspect of your use case, surely a start date (in ISO0861) and a recur interval is all you need?

If you need great support in JavaScript, [moment.js](http://momentjs.com) is the defacto standard, and there is an [excellent plugin](http://momentjs.com/docs/#/plugins/recur/) to deal with recurring instances.

**Comment by stevage** [comment]
> surely ISO8601 dates are the most widely supported string format for dates?

Yes, of course - for the actual date part. ISO8601 includes some pretty funky things though. These are valid dates: '2015-128', '2015-W33-1'... let alone durations and all the timezone stuff.

> If you just mean the recurring aspect of your use case, surely a start date (in ISO0861) and a recur interval is all you need?

It's "all you need" to address the machine-readable part, but it's still not very user friendly. I discovered when actually trying to use the data that you really want access to a simple "Monday"-type string.

> If you need great support in JavaScript, moment.js is the defacto standard, and there is an excellent plugin to deal with recurring instances.

You'd think so :)

http://stackoverflow.com/questions/29457872/do-any-javascript-libraries-support-iso8601-recurring-intervals

**Comment by pwalsh** [comment]
Oh well, I've never even seen the R/ thing to declare the intervals as part of the iso format, so I stand corrected on that. Getting the day name is widely supported though.
