### ISSUE TITLE
Consider documenting planning/development application schema

### ISSUE THREAD

**Issue by CloCkWeRX** [OKFNau/open-council-data#18]
The folks over at https://github.com/openaustralia/ herd a number of scrapers of development application data over at https://github.com/planningalerts-scrapers 

The very minimum of this data set tends to be:
- info_url - where to find out more about the application
- council_reference 
- date_received - date the application was received by the council
- address
  *\*  A geojson representation of the parcel or a point would be even better in a lot of cases!
- description - very brief summary of what is in the application itself

https://www.planningalerts.org.au/getinvolved has a more detailed set of tools, etc.

Right now it's scraping focused even though there are a lot of standardised tools out there - I suspect it's a visibility problem in part; where a documented schema and examples of other councils using it would help.

**Comment by stevage** [comment]
Hey, nice to hear from you - I seem to see your username all over OpenStreetMap, Mapillary, etc.

When I've asked about planning data in the past, it tends to get complicated pretty quickly. Planning processes involve both local and state government, and there's all kinds of confidential data, and data that is only semi-public. For example, they're ok with it being available on request, but not publishing to the world. I wonder how they feel about their planning registers being scraped?

Anyway I'll bring it up on the [open council data google group](https://groups.google.com/forum/#!forum/opendatagroup). If there are any takers to publish this data (or if you know any?) I'd be very happy to help standardise.

**Comment by CloCkWeRX** [comment]
I think a majority of Vic councils are covered by SPEAR (http://www.spear.land.vic.gov.au/spear/pages/about/what-is-spear/overview.shtml) - unfortunately it's other councils in other states that tend to have a large variety of systems and no benefits of scale.

I'd suggest the smallest, easiest part of the puzzle is much of what planningalerts etc already does - focuses on published applications for public comment pending approval

**Comment by maxious** [comment]
Gold Coast City Council publish a dataset every couple of months about historical DAs and their outcomes https://data.gov.au/dataset/property-application

**Comment by stevage** [comment]
@CloCkWeRX Looks like there is some interest from City of Melbourne and Geelong, want to get involved on https://groups.google.com/forum/#!forum/opencouncildata ?

**Comment by Wjrmc** [comment]
Like many other Vic councils Geelong also use Spear but I would be interested in looking at how we can make our planning data more usable and accessible. As mentioned the Mosman council example (http://portal.mosman.nsw.gov.au/pages/xc.track/RSS.aspx?u=7days) is really impressive and something that I would want to strive towards.

**Comment by CloCkWeRX** [comment]
> Looks like there is some interest from City of Melbourne and Geelong, want to get involved on https://groups.google.com/forum/#!forum/opencouncildata ?

Sure; uh I think I'm stuck waiting approval though!

>  City of Melbourne, Geelong

Neat! Re Melbourne, 
https://morph.io/planningalerts-scrapers/melbourne is the current feed that planning alerts derives from this, though having geocodes or stronger property identifiers would be neat for linking to gnaf/cadlite data.

It's not obvious from the website, but I could probably find out stats to see how many people are subscribed to it if interested - would be interesting to know how that translates into feedback if any.

Another use case I keep meaning to do fully is "OpenStreetMap buildings with a development application on them" - http://www.openstreetmap.org/note/new#map=14/-34.8506/138.5216&layers=N is me doing it in my local area manually; but in an area like Geelong with all of the buildings imported there plus newer satellite imagery you potentially get a small feed of updates back from the community and on the ground observations. 
The benefit in my area is a pretty up to date address map/better car GPS navigation tools.

> Mosman council example 

Yeah I really like the map presentation of the data; it makes it a heck of a lot easier (Oh, _that_ building is being knocked down/changing use) than a table of addresses! Being able to get at the GeoRSS as well is great.

So the really good thing about this is a lot of councils use this XC.Track platform - "ICON Software Solutions". What's a bit more frustrating is that a lot of them simply haven't configured their installation to publish RSS! Doh! That, or upgrades tend to break URIs :(

Even something as simple as a HOWTO coupled with real world examples of the benefits would probably change a few minds/prompt the data to open up - but being an outsider without access to a demo version of the software makes that tricky.

**Comment by mswards** [comment]
I have just released the Ballarat planning applications on advertising - https://data.gov.au/dataset/ballarat-planning-applications-currently-on-advertising

I am planning on having all existing approved applications released within the next week or so.

**Comment by stevage** [comment]
Hi Matt,
  That's awesome. As I'm not so familiar with planning, what proportion of
the total planning process do "approved" and "on advertising" cover?

Steve

**Comment by mswards** [comment]
Hi Steve,

On advertising is a very small proportion. I will hopefully next week release all approved planning permits on record at Council. Not all existing will have lat/long but everything forward most definitely will. This will be around 20,000 records updated with newly approved applications daily. Last year there were around 1299 applications received.

**Comment by stevage** [comment]
Thanks to @henare I see that there is a fully developed planning development application standard, ATDIS: https://www.planningalerts.org.au/atdis/specification

**Comment by CloCkWeRX** [comment]
Closing this off for ATDIS which seems to be working well for a number of NSW councils (https://github.com/openaustralia/planningalerts/issues/920 for example)
