### ISSUE TITLE
Garbage Collection Column Names

### ISSUE THREAD

**Issue by Wjrmc** [OKFNau/open-council-data#2]
When converting Geelong Waste Collection data to ESRI shapefiles we are getting some limitations on field column name character limit. This means some fields will have issues when exporting to ESRI formats. 

The affected columns are:
- rubbish_schedule
- recycling_schedule
- green_schedule
- description
- rubbish_comment
- recycling_comment
- green_comment
- missed_collection_phone

Screenshot of affected fields below:

![image](https://cloud.githubusercontent.com/assets/8185097/5656298/66485b90-972e-11e4-8daf-135b05101e27.png)

**Comment by stevage** [comment]
Thanks for the report. Ok, I've made shorter names. Pity about this limitation - it definitely makes the names less intuitive.
