### ISSUE TITLE
Garbage collection polygons in rural areas

### ISSUE THREAD

**Issue by barretthigman** [OKFNau/open-council-data#3]
Hi,

I'm not sure if this is the best place to post this but I would be interested in your opinion about a problem I have always encountered when creating garbage collection polygons in rural areas. My main issue is that not all residents in rural areas receive garbage and/or recycling collection and often those that do are a significant distance from each other (we have 4800 sq km of land but only 8% is freehold). In order to ensure that internal staff don't assume that all freehold land in the shire has garbage collection I create the garbage collection areas on a property by property basis rather than large individual polygons for each service area. The way I do this (in an automated process) is as follows:
1. The route taken by garbage collection trucks for each day/week is maintained manually by our waste staff using our GIS
2. I use our rates and property database to find which properties pay for waste/recycling collection
3. I use a nearest neighbour process whereby the Vicmap address location of those properties that have a collection are compared against the collection routes, the closest route to the address point providing the collection details for that property

The resulting dataset looks like this:

![image](https://cloud.githubusercontent.com/assets/10764883/5971468/53c7b510-a89a-11e4-8726-7e7d0a75311b.png)

Of course I could publish this dataset but then there are potential privacy issues as it is possible to see down to a property level as to who pays or doesn't pay for garbage collection.

Your thoughts would be appreciated.

Cheers,
Barrett
(Alpine Shire Council)

**Comment by Wjrmc** [comment]
Hi Barrett,

Although this is done at a property level, I expect you still might have 'collection zones' as well as the different days that different bins are collected? 

Would it be an option to only show the collection zones with the explicit statement that these areas reflect the zones but only after the resident pays for the service does this happen. 

This way, existing residents can see their collection days, as well as potential residents who are thinking of moving to the Alpine region. It would also mean that it would connect better with a state-wide waste collection zone dataset.

Will

**Comment by barretthigman** [comment]
Hi Will,

We do have zones, in that properties in different areas have their waste collected on different days/weeks. However, in the current dataset each property holds that information. The problem I have is creating that generic overview dataset that says all properties in a particular area has waste collected on this day/week as it is not just based on capacity to pay. Some properties will never be offered a service as they live too far away from the truck route, whereas some property owners drag their bins several kilometres to a location that the truck can collect them from. There is no consistency in the rural areas that can be used to determine both existing and potential properties for waste collection and, therefore, the overall collection zone.

I guess my main problem is knowing how to fill in the gaps between existing properties with the same collection schedule... I'll ponder it a bit more :)

Cheers,
Barrett

**Comment by stevage** [comment]
Does your GIS have any way to generate a [convex hull](https://github.com/Turfjs/turf-convex)? Ultimately, the collection polygon should answer the question "if I live in this zone, and I have signed up for garbage collection, what night is bin night"? It's ok if it includes properties that don't or can't get a collection.

You might be interested to compare the approaches of Golden Plains, Colac-Otway and Corangamite regarding rural collections:

![screenshot 2015-04-18 22 25 06](https://cloud.githubusercontent.com/assets/678344/7215409/debd9d80-e619-11e4-9b0f-f1393b0dbe82.png)

**Comment by stevage** [comment]
Closing as Alpine Shire published their garbage zones! :)
