### ISSUE TITLE
Include recommended dataset names

### ISSUE THREAD

**Issue by stevage** [OKFNau/open-council-data#4]
The standards should incorporate recommendations on how to name datasets, where to publish them, how to tag, etc.

**Comment by Wjrmc** [comment]
Good point. Any ideas where to start?

--- Original Message ---

**Comment by stevage** [comment]
How about:
- name: <council name> Garbage Collection Schedules
- where: data.gov.au
- tags: garbage, rubbish, waste, collection, bin night, area, zone

?

Steve

**Comment by Wjrmc** [comment]
Yeah looks good to me. Should there be a tag to show that the dataset is using open council data standards? Might make it easier to do quick checks to see how many are using the standards down the track? Ie - ocdc (open council data compliant)

**Comment by stevage** [comment]
Great idea. How about: opencouncildata-garbage-1.0, opencouncildata-parks-1.0 etc? Then it's as precise as possible.

**Comment by Wjrmc** [comment]
It's good but is it too long for a 'tag'?

--- Original Message ---

**Comment by stevage** [comment]
Good question, I've asked data.gov.au on Twitter.

**Comment by stevage** [comment]
Added here: https://github.com/OKFNau/open-council-data/commit/6870a338bd28d3130a1d966c7ea0f344879d8d2f
