### ISSUE TITLE
Addition of Standard: Public Bins

### ISSUE THREAD

**Issue by SkeenP-NGSC** [OKFNau/open-council-data#45]
Another option for a standard could be the location of public bins. Something like the following:
# Public Bins 0.1

**General recommendations:**

Format Point data. CSV (preferred), GeoJSON 
Dataset name [Council name] Public Bins 
data.gov.au tag public-bins, ocd-public-bins, ocd-public-bins-0.1 

**Required fields**

lat, lon Latitude, longitude, decimal degrees. (EPSG:4326) 

**Recommended fields**

operator The council (or company) that operates the station. 
contact_ph The station's telephone number. 

**Optional fields**

location Description of where the bin is located. 
info_url URL of area where bin is located (e.g. park, facility, etc) or of operator responcibile for managing the bin. 
type Type of bin. Could be one of cigarette, waste or recycling

**Comment by stevage** [comment]
Thanks for the suggestion! I'm a little concerned about having a large number of specific standards, so maybe it would be better to group this in a more general "street furniture" standard? Obviously the downside is you can't have as many specific attributes though.

**Comment by SkeenP-NGSC** [comment]
Would fit nicely into street furniture :).
