### ISSUE TITLE
Addition of Standard: Councillers

### ISSUE THREAD

**Issue by SkeenP-NGSC** [OKFNau/open-council-data#46]
Data on councillors can be very useful, and is being showed off very well by Groundtruths POZI. A standard could be used to keep web applications up to speed on a regions representitives. Multiple data rows can be provided for each ward, multiple wards can be described in the one file.
# Councillors 0.1

**General recommendations:**

Format: CSV, RSS
Dataset name: [Council name] councillors
data.gov.au tag: opencouncildata-councilers-0.1

**Required fields**

ward_id: id of ward as per vec/vicmap classification

**Optional fields**

elected_date: Data member was elected
councillor: The name of the councillor that currently represents the region.
portfolio: The portfolio held by the councillor, if any.
phone_office: Office phone number
phone_mobile: Mobile phone number
email: Email address
url_bio: Biographical URL
image_url: Image URL

Credit to Groundtruth's POZI for direction on the additional fields.

**Comment by stevage** [comment]
Great suggestion. By "elected_date" do you mean specifically the date of the election, or the start of their term? (Is there a difference in local government?)

I'd probably suggest having instead: `term_start` and optional `term_end`, which also leaves open the possibility of including past terms included.

**Comment by stevage** [comment]
Ok, I've made a few modifications (eg, including `ward_name`). [Have a look](https://github.com/OpenCouncilData/ocd-standards/blob/gh-pages/_posts/2016-04-14-councillors.md).

**Comment by SkeenP-NGSC** [comment]
Looks good, thanks. I think term start and end are both acceptable in lieu of elected date.
