### ISSUE TITLE
Planning Permit Proposal Standard

### ISSUE THREAD

**Issue by Wjrmc** [OKFNau/open-council-data#49]
Hi all,

If Planning permits needs a standard we propose the following (feedback welcome! @CloCkWeRX @henare):

Recommended fields

Field Alias, Name, (example value)
Application number - app_num (string TP-2016-180)
Application date - app_date (date 14/01/2016)
Latitude - lat (float -38.444)
Longitude - lon (float 144.567)
Property Key - prop_key (integer 1034521)
Application description - app_desc (string)
Authority - auth_name (string - City of Melbourne, City of Geelong, Department of Environment Land Water and Planning)
Application status - status ()
Expiry date - exp_date

Optional
Application Plans URL - plans_url 
Number of objections received - num_objections

**Comment by CloCkWeRX** [comment]
Check out ATDIS - https://www.planningalerts.org.au/atdis/specification

Sample feed in the wild: http://horizon.gundagai.nsw.gov.au/Horizon//@@horizondap@@/atdis/1.0/applications.json - tends to support params like 

```
?lodgement_date_end=2016-03-22&lodgement_date_start=2016-02-21&page=2
```

**Comment by Wjrmc** [comment]
Oh perfect... Checking it out.

Sent using CloudMagic Email [https://cloudmagic.com/k/d/mailapp?ct=pa&cv=8.3.8&pv=5.1.1&source=email_footer_2] On Wed, Mar 23, 2016 at 11:30 AM, CloCkWeRX < notifications@github.com [notifications@github.com] > wrote:
Check out ATDIS - https://www.planningalerts.org.au/atdis/specification [https://www.planningalerts.org.au/atdis/specification]

**Comment by CloCkWeRX** [comment]
#18

**Comment by Wjrmc** [comment]
The spec looks great. We're currently working on getting our planning data to this standard.
