### ISSUE TITLE
Incomplete data

### ISSUE THREAD

**Issue by Wjrmc** [OKFNau/open-council-data#5]
If a council is still collecting information about a data set, say public toilets. They have all of the toilet locations, and are collecting additional data, such as open times, wheelchair access, etc.

If they have some information for these fields, ie - some toilets have an opening time, but others havent yet been collected, is it worth still uploading the data? 

For field values that have not yet been collected, should these just be left blank? 

Toilets is a simple example but other more complex data may take months/years to get complete data set.

**Comment by stevage** [comment]
Yeah, I think generally any row that has all its "required" fields (in this case, just lat and lon) is fine to include - other fields should just be blank (either ,, or ,"", in CSV).
