### ISSUE TITLE
Toilets 1.0

### ISSUE THREAD

**Issue by Wjrmc** [OKFNau/open-council-data#6]
Why does week_open have 00:00 for always open, but week_close has 24:00 for always open? 

week_open: What time the toilets open on weekdays, in 0-padded 24 hour time. 00:00 for always open.
week_close: What time the toilets close on weekdays, in 24 hour time. 24:00 for always open

**Comment by stevage** [comment]
Yeah, it's a bit odd, maybe too confusing. It was intentional, in that always open would be "00:00-24:00", but I think we should come up with something better.

**Comment by stevage** [comment]
Hmm, can't think of much better, and also realise there was no explicit way to indicate if the toilets are closed all day on a certain day. So for want of better, sticking with 00:00, 24:00 for always open, and 00:00, 00:00 for always closed.
