### ISSUE TITLE
Guidance on projections

### ISSUE THREAD

**Issue by stevage** [OKFNau/open-council-data#8]
GeoJSON representations should all be in EPSG:3857 (Web Mercator). I had forgotten there was a choice. Surprisingly diverse range of choices in use.

**Comment by Wjrmc** [comment]
Is this different for other formats?

--- Original Message ---

**Comment by stevage** [comment]
Well, CSV in particular doesn't leave open the possibility of any CRS other
than lat/lon.

**Comment by stevage** [comment]
Oh, god, how naive I was. https://data.sa.gov.au/dataset/street-trees

The CSV uses eastings and northings, which are in the UTM zone correct for Adelaide - but none of that is documented.
